In [2]:
import pandas as pd

In [3]:
file_path = "/Users/gongwenkai/Projects/Portfolio/Procurement_Spending_Analysis/01_Raw_Data/spend_analysis_dataset.csv"
df = pd.read_csv(file_path)

In [4]:
first_five_rows = df.head()
first_five_rows

,TransactionID,ItemName,Category,Quantity,UnitPrice,TotalCost,PurchaseDate,Supplier,Buyer
0,TXN001,Desk Chair,Furniture,10,113.15,1131.50,2024-04-19,TechMart Inc.,Kelly Joseph
1,TXN002,Stapler,Office Supplies,16,12.62,201.92,2024-07-06,CloudSoft Corp.,Kelly Joseph
2,TXN003,Annual Software License,Software,1,5649.34,5649.34,2024-09-10,TechMart Inc.,Kelly Joseph
3,TXN004,Notepad,Stationery,13,2.92,37.96,2024-01-21,FurniWorks Ltd.,Luis Holland
4,TXN005,Notepad,Stationery,19,1.39,26.41,2024-02-03,TechMart Inc.,Cynthia Jenkins

In [5]:
data_shape = df.shape
data_shape

(500, 9)

In [6]:
column_names = df.columns
column_names

Index(['TransactionID', 'ItemName', 'Category', 'Quantity', 'UnitPrice',
       'TotalCost', 'PurchaseDate', 'Supplier', 'Buyer'],
      dtype='object')

In [7]:
column_types = df.dtypes
column_types

TransactionID     object
ItemName          object
Category          object
Quantity           int64
UnitPrice        float64
TotalCost        float64
PurchaseDate      object
Supplier          object
Buyer             object
dtype: object

In [8]:
missing_values = df.isnull()
missing_count = missing_values.sum()

In [9]:
missing_count

TransactionID    0
ItemName         0
Category         0
Quantity         0
UnitPrice        0
TotalCost        0
PurchaseDate     0
Supplier         0
Buyer            0
dtype: int64

In [10]:
duplicate_rows = df.duplicated()
duplicate_count = duplicate_rows.sum()

In [11]:
duplicate_count

np.int64(0)

In [12]:
date_samples = df["PurchaseDate"].head()
date_samples

0    2024-04-19
1    2024-07-06
2    2024-09-10
3    2024-01-21
4    2024-02-03
Name: PurchaseDate, dtype: object

In [13]:
quantity_is_negative = df["Quantity"] < 0
negative_quantity_count = quantity_is_negative.sum()

In [14]:
negative_quantity_count

np.int64(0)

In [15]:
UnitPrice_is_negative = df["UnitPrice"] < 0
negative_UnitPrice_count = UnitPrice_is_negative.sum()

In [16]:
negative_UnitPrice_count

np.int64(0)

In [17]:
supplier_names = df["Supplier"].unique()
supplier_names

array(['TechMart Inc.', 'CloudSoft Corp.', 'FurniWorks Ltd.',
       'OfficeSupplies Co.', 'QuickDeliver Ltd.'], dtype=object)

In [18]:
category_names = df["Category"].unique()
category_names

array(['Furniture', 'Office Supplies', 'Software', 'Stationery',
       'Electronics', 'Accessories'], dtype=object)

In [19]:
df_clean = df.copy()

In [20]:
df_clean = df_clean.drop_duplicates()

In [21]:
df_clean.shape

(500, 9)

In [22]:
purchase_date_text = df_clean["PurchaseDate"]

In [23]:
purchase_date = pd.to_datetime(purchase_date_text)

In [24]:
df_clean["PurchaseDate"] = purchase_date

In [25]:
purchase_date_type = df_clean["PurchaseDate"].dtype
purchase_date_type

dtype('<M8[ns]')

In [26]:
supplier_text = df_clean["Supplier"]
supplier_text = supplier_text.str.strip()

In [27]:
df_clean["Supplier"] = supplier_text

In [28]:
category_text = df_clean["Category"]
category_text = category_text.str.strip()

In [29]:
df_clean["Category"] = category_text

In [30]:
spend_amount = df_clean["TotalCost"]

In [31]:
df_clean["Spend"] = spend_amount

In [32]:
month_value = purchase_date.dt.strftime("%Y-%m")

In [33]:
df_clean["Month"] = month_value

In [34]:
supplier_column = df_clean["Supplier"]
spend_column = df_clean["Spend"]

In [35]:
supplier_groups = spend_column.groupby(supplier_column)

In [36]:
supplier_spend = supplier_groups.sum()
supplier_spend

Supplier
CloudSoft Corp.       200073.64
FurniWorks Ltd.       202810.72
OfficeSupplies Co.    223580.85
QuickDeliver Ltd.     285353.59
TechMart Inc.         328761.73
Name: Spend, dtype: float64

In [37]:
supplier_spend_table = supplier_spend.reset_index()
supplier_spend_table

             Supplier      Spend
0     CloudSoft Corp.  200073.64
1     FurniWorks Ltd.  202810.72
2  OfficeSupplies Co.  223580.85
3   QuickDeliver Ltd.  285353.59
4       TechMart Inc.  328761.73

In [38]:
supplier_spend_table = supplier_spend_table.sort_values("Spend", ascending=False)
supplier_spend_table

             Supplier      Spend
4       TechMart Inc.  328761.73
3   QuickDeliver Ltd.  285353.59
2  OfficeSupplies Co.  223580.85
1     FurniWorks Ltd.  202810.72
0     CloudSoft Corp.  200073.64

In [39]:
category_column = df_clean["Category"]
category_groups = spend_column.groupby(category_column)

In [40]:
category_spend = category_groups.sum()
category_spend

Category
Accessories         20857.24
Electronics        697805.23
Furniture          172818.61
Office Supplies      6328.27
Software           336018.00
Stationery           6753.18
Name: Spend, dtype: float64

In [41]:
category_spend_table = category_spend.reset_index()
category_spend_table

          Category      Spend
0      Accessories   20857.24
1      Electronics  697805.23
2        Furniture  172818.61
3  Office Supplies    6328.27
4         Software  336018.00
5       Stationery    6753.18

In [42]:
category_spend_table = category_spend_table.sort_values("Spend", ascending=False)
category_spend_table

          Category      Spend
1      Electronics  697805.23
4         Software  336018.00
2        Furniture  172818.61
0      Accessories   20857.24
5       Stationery    6753.18
3  Office Supplies    6328.27

In [43]:
month_column = df_clean["Month"]
month_groups = spend_column.groupby(month_column)

In [44]:
monthly_spend = month_groups.sum()
monthly_spend

Month
2024-01    101523.95
2024-02     78544.71
2024-03    123639.03
2024-04    119348.90
2024-05    117917.38
2024-06     87118.54
2024-07     76055.66
2024-08     77222.97
2024-09    125187.25
2024-10    121217.02
2024-11    114299.46
2024-12     98505.66
Name: Spend, dtype: float64

In [45]:
monthly_spend_table = monthly_spend.reset_index()
monthly_spend_table

      Month      Spend
0   2024-01  101523.95
1   2024-02   78544.71
2   2024-03  123639.03
3   2024-04  119348.90
4   2024-05  117917.38
5   2024-06   87118.54
6   2024-07   76055.66
7   2024-08   77222.97
8   2024-09  125187.25
9   2024-10  121217.02
10  2024-11  114299.46
11  2024-12   98505.66

In [46]:
total_spend = spend_column.sum()
total_spend

np.float64(1240580.5299999998)

In [47]:
supplier_count = supplier_column.nunique()
supplier_count

5

In [48]:
transaction_count = df_clean["TransactionID"].nunique()
transaction_count

500

In [49]:
output_file = "procurement_spend_analysis.xlsx"

In [50]:
excel_writer = pd.ExcelWriter(output_file)

In [51]:
df_clean.to_excel(excel_writer, sheet_name="Cleaned Data", index=False)

In [52]:
supplier_spend_table.to_excel(excel_writer, sheet_name="Supplier Spend", index=False)

In [53]:
category_spend_table.to_excel(excel_writer, sheet_name="Category Spend", index=False)

In [54]:
monthly_spend_table.to_excel(excel_writer, sheet_name="Monthly Spend", index=False)

In [55]:
excel_writer.close()

In [57]:
(df["Quantity"] == 1).sum()

np.int64(67)

In [58]:
(df["TotalCost"] > 10000).sum()

np.int64(26)